version: '3'
services:
  front:
    image: mvelasquez10/calculator:latest
    container_name: front
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
  back:
    image: mvelasquez10/calculator-api:latest
    container_name: back
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
