name: Tests Cypress
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Up calculator front
        run: docker run --name front -p 80:80 -d mvelasquez10/calculator:latest 
      - name: Up calculator back
        run: docker run --name back -p 5000:80 -d mvelasquez10/calculator-api:latest 
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress Calculator Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm run cypress:runCalculatorTest
          browser: chrome
          record: true
          parallel: false 
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Cypress Login Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm run cypress:runLoginTest
          browser: chrome
          record: true
          parallel: false 
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Shutdown calculator application
        run: docker stop front back