name: Tests Cypress
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Up calculator front
        run: docker run --name front -p 80:80 -d mvelasquez10/calculator:latest
      - name: Up calculator back
        run: docker run --name back -p 5000:80 -d mvelasquez10/calculator-api:latest

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm run cypress:runAllTest
          browser: chrome
          continue-on-error: true
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Shutdown calculator application
        run: docker stop front back

      - name: Publish reports
        uses: PavanMudigonda/html-reporter-github-pages@v1.0
        id: test-report
        with:
          test_results: cypress/reports/
          gh_pages: gh-pages
          results_history: results-history
          keep_reports: 10

      - uses: actions/upload-artifact@v3
        with:
          name: CypressReport
          path: cypress/reports/

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: https://edisonvasquez16.github.io/DemoCypress/
          path: https://edisonvasquez16.github.io/DemoCypress/