name: Cypress Tests
on: [push]
jobs:
  RunWorkflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Up calculator app
        run: | 
          docker run --name front -p 80:80 -d mvelasquez10/calculator:latest
          docker run --name back -p 5000:80 -d mvelasquez10/calculator-api:latest
          rm -rf ./public ./videos ./results index.html
          mkdir public
          mkdir videos
          mkdir results
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress Tests
        uses: cypress-io/github-action@v4
        if: always()
        with:
          start: npm run cypress:runAllTest
          browser: chrome
          record: true
          parallel: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Shutdown calculator application
        run: docker stop front back
        if: always()

      - name: Publish single report
        if: always()
        uses: PavanMudigonda/html-reporter-github-pages@v1.0
        id: CypressReport
        with:
          test_results: cypress/results/
          gh_pages: gh-pages
          results_history: results-history
          keep_reports: 10

      - name: Create artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: CypressReport
          path: cypress/results/

      - name: Generate report
        if: always()
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          npm run report:merge
          npm run report:generate

      - name: Push report page
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
          user_name: 'edisonvasquez16'
          user_email: 'evasquez16.ev@gmail.com'