name: Logint Test Cypress
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001 
    steps:
      - uses: actions/checkout@v2

      - name: Persist Next.js build cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-

      - name: Install and cache Cypress and npm dependencies, and build frontend server
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          build: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run cypress:runLoginTest
          wait-on: 'http://localhost:3000'
          browser: chrome
          record: true
          parallel: false 
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Save built frontend server
        uses: actions/upload-artifact@v2
        with:
          name: frontend-server
          path: .next
          if-no-files-found: error